# AI Pricing & Demand Forecasting Platform

## Notebook 01 – Data Understanding

### Business Problem

Retail companies lose millions due to poor pricing decisions, inaccurate demand forecasting, and inventory imbalance.

The objective of this project is to build an AI-powered pricing and demand forecasting system that helps business managers make data-driven decisions.

---

### Objectives

- Understand the dataset
- Identify important business variables
- Assess data quality
- Explore the structure of retail operations
- Prepare data for machine learning

In [1]:
# Import required libraries

import pandas as pd
import numpy as np

In [8]:
import os

print("Current Folder:", os.getcwd())
print("Files in Current Folder:", os.listdir())
print("Project Root Files:", os.listdir(".."))
print("Data Folder:", os.listdir("../data"))
print("Raw Folder:", os.listdir("../data/raw"))

Current Folder: c:\AI-Pricing-Demand-Forecasting\notebooks
Files in Current Folder: ['01_data_understanding.ipynb']
Project Root Files: ['.venv', 'data', 'notebooks']
Data Folder: ['raw']
Raw Folder: ['retail_store_inventory (1).csv']

In [9]:
df = pd.read_csv("../data/raw/retail_store_inventory (1).csv")

In [10]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [11]:
# Dataset dimensions

rows, columns = df.shape

print(f"Number of Rows    : {rows}")
print(f"Number of Columns : {columns}")

Number of Rows    : 73100
Number of Columns : 15

In [12]:
# Display all column names

for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

1. Date
2. Store ID
3. Product ID
4. Category
5. Region
6. Inventory Level
7. Units Sold
8. Units Ordered
9. Demand Forecast
10. Price
11. Discount
12. Weather Condition
13. Holiday/Promotion
14. Competitor Pricing
15. Seasonality

In [13]:
# Check data types

df.dtypes

Date                      str
Store ID                  str
Product ID                str
Category                  str
Region                    str
Inventory Level         int64
Units Sold              int64
Units Ordered           int64
Demand Forecast       float64
Price                 float64
Discount                int64
Weather Condition         str
Holiday/Promotion       int64
Competitor Pricing    float64
Seasonality               str
dtype: object

In [14]:
# Missing values

missing_values = df.isnull().sum()

missing_values

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [15]:
# Check duplicate rows

duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 0

In [16]:
# Statistical Summary

df.describe()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Holiday/Promotion,Competitor Pricing
count,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,0.497305,55.146077
std,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,0.499996,26.191408
min,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,0.000000,5.030000
25%,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,0.000000,32.680000
50%,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,0.000000,55.010000
75%,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,1.000000,77.820000
max,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,1.000000,104.940000

# Business Observations

### Initial Findings

- The dataset contains historical retail inventory and sales information.
- Multiple business factors influence demand including:
  - Price
  - Discount
  - Competitor Pricing
  - Inventory
  - Seasonality
  - Weather
  - Promotions
- This dataset is suitable for:
  - Demand Forecasting
  - Dynamic Pricing
  - Inventory Optimization
  - Executive Decision Support